export const sampleTags = [
  { id: "1", name: "grammar", color: "#E57373" },
  { id: "2", name: "vocabulary", color: "#F06292" },
  { id: "3", name: "phrasal verbs", color: "#BA68C8" },
  { id: "4", name: "idioms", color: "#9575CD" },
  { id: "5", name: "expressions", color: "#64B5F6" },
  { id: "6", name: "listening", color: "#4FC3F7" },
  { id: "7", name: "reading", color: "#4DD0E1" },
  { id: "8", name: "speaking", color: "#4DB6AC" },
  { id: "9", name: "writing", color: "#81C784" },
  { id: "10", name: "adjectives", color: "#AED581" },
  { id: "11", name: "verbs", color: "#DCE775" },
  { id: "12", name: "nouns", color: "#FFD54F" },
  { id: "13", name: "adverbs", color: "#FFB74D" },
  { id: "14", name: "prepositions", color: "#FF8A65" },
  { id: "15", name: "pronunciation", color: "#A1887F" },
  { id: "16", name: "TOEFL", color: "#90A4AE" },
  { id: "17", name: "IELTS", color: "#B0BEC5" },
  { id: "18", name: "slang", color: "#F48FB1" },
  { id: "19", name: "formality", color: "#CE93D8" },
  { id: "20", name: "collocations", color: "#FFF176" },
  { id: "21", name: "synonyms", color: "#A5D6A7" },
  { id: "22", name: "antonyms", color: "#81D4FA" },
  { id: "23", name: "false friends", color: "#E1BEE7" },
  { id: "24", name: "british english", color: "#B39DDB" },
  { id: "25", name: "american english", color: "#FFCC80" },
  { id: "26", name: "irregular verbs", color: "#80CBC4" },
  { id: "27", name: "articles", color: "#BCAAA4" },
  { id: "28", name: "past tense", color: "#E6EE9C" },
  { id: "29", name: "present tense", color: "#FFF59D" },
  { id: "30", name: "future tense", color: "#FFE082" },
  { id: "31", name: "questions", color: "#FFAB91" },
  { id: "32", name: "answers", color: "#B0BEC5" },
  { id: "33", name: "intermediate", color: "#A1887F" },
  { id: "34", name: "beginner", color: "#CE93D8" },
  { id: "35", name: "advanced", color: "#64B5F6" },
  { id: "36", name: "negation", color: "#F8BBD0" },
  { id: "37", name: "affirmation", color: "#DCEDC8" },
  { id: "38", name: "commands", color: "#F0F4C3" },
  { id: "39", name: "conditional", color: "#D1C4E9" },
  { id: "40", name: "comparatives", color: "#FFECB3" },
  { id: "41", name: "superlatives", color: "#FFE0B2" },
  { id: "42", name: "homophones", color: "#C5E1A5" },
  { id: "43", name: "homonyms", color: "#B2EBF2" },
  { id: "44", name: "acronyms", color: "#E0F2F1" },
  { id: "45", name: "contractions", color: "#D7CCC8" },
  { id: "46", name: "conjunctions", color: "#FFF8E1" },
  { id: "47", name: "articles", color: "#CFD8DC" },
  { id: "48", name: "determiners", color: "#FFCDD2" },
  { id: "49", name: "question tags", color: "#D1C4E9" },
  { id: "50", name: "modals", color: "#B2DFDB" },
  { id: "51", name: "passive voice", color: "#EF9A9A" },
  { id: "52", name: "active voice", color: "#F48FB1" },
  { id: "53", name: "gerunds", color: "#CE93D8" },
  { id: "54", name: "infinitives", color: "#B39DDB" },
  { id: "55", name: "clauses", color: "#9FA8DA" },
  { id: "56", name: "reported speech", color: "#90CAF9" },
  { id: "57", name: "direct speech", color: "#81D4FA" },
  { id: "58", name: "conversation", color: "#80DEEA" },
  { id: "59", name: "translation", color: "#80CBC4" },
  { id: "60", name: "punctuation", color: "#A5D6A7" },
  { id: "61", name: "pronouns", color: "#C5E1A5" },
  { id: "62", name: "possessives", color: "#E6EE9C" },
  { id: "63", name: "question words", color: "#FFF59D" },
  { id: "64", name: "phonetical symbols", color: "#FFE082" },
  { id: "65", name: "intonation", color: "#FFCC80" },
  { id: "66", name: "stress", color: "#FFAB91" },
  { id: "67", name: "business english", color: "#BCAAA4" },
  { id: "68", name: "academic english", color: "#B0BEC5" },
  { id: "69", name: "informal english", color: "#B2EBF2" },
  { id: "70", name: "formal english", color: "#D1C4E9" },
  { id: "71", name: "daily expressions", color: "#E1BEE7" },
  { id: "72", name: "emotions", color: "#F8BBD0" },
  { id: "73", name: "weather", color: "#D7CCC8" },
  { id: "74", name: "numbers", color: "#FFF8E1" },
  { id: "75", name: "dates", color: "#CFD8DC" },
  { id: "76", name: "colors", color: "#F5F5F5" },
  { id: "77", name: "family", color: "#FFE0B2" },
  { id: "78", name: "food", color: "#FFECB3" },
  { id: "79", name: "health", color: "#DCEDC8" },
  { id: "80", name: "travel", color: "#C8E6C9" },
  { id: "81", name: "jobs", color: "#B2DFDB" },
  { id: "82", name: "technology", color: "#B3E5FC" },
  { id: "83", name: "sports", color: "#B2EBF2" },
  { id: "84", name: "entertainment", color: "#D1C4E9" },
  { id: "85", name: "school", color: "#E1BEE7" },
  { id: "86", name: "shopping", color: "#FFCCBC" },
  { id: "87", name: "money", color: "#F0F4C3" },
  { id: "88", name: "transport", color: "#E6EE9C" },
  { id: "89", name: "environment", color: "#DCEDC8" },
  { id: "90", name: "descriptions", color: "#F8BBD0" },
  { id: "91", name: "comparisons", color: "#E0F7FA" },
  { id: "92", name: "habits", color: "#FFF3E0" },
  { id: "93", name: "goals", color: "#FFCDD2" },
  { id: "94", name: "stories", color: "#F3E5F5" },
  { id: "95", name: "questions & answers", color: "#E0F2F1" },
  { id: "96", name: "common mistakes", color: "#FBE9E7" },
  { id: "97", name: "tips", color: "#EDE7F6" },
  { id: "98", name: "review", color: "#ECEFF1" },
  { id: "99", name: "revision", color: "#F1F8E9" },
  { id: "100", name: "practice", color: "#FFFDE7" },
];
