export const sampleWords = [
  {
    word: "Tree",
    translation: "árbol",
    definition: "A perennial plant with an elongated stem, or trunk.",
    examples: [
      "The tree in my backyard is over 100 years old.",
      "She sat under a tree to read a book.",
    ],
    tags: [{ id: "V808976mg0fJgf7kwfzd", name: "animal", color: "#FF8A65" }],
    type: "sustantivo",
    createdAt: "2025-06-25T12:00:00.000Z",
    updatedAt: "2025-06-25T12:00:00.000Z",
    isLearned: false,
  },
  {
    word: "Quickly",
    translation: "rápidamente",
    definition: "At a fast speed; rapidly.",
    examples: [
      "She ran quickly to catch the bus.",
      "Finish your homework quickly so you can rest.",
    ],
    tags: [{ id: "ZZZSfatMkgfxziESFEsv", name: "rose", color: "#E1BEE7" }],
    type: "adverbio",
    createdAt: "2025-06-25T13:30:00.000Z",
    updatedAt: "2025-06-25T13:30:00.000Z",
    isLearned: false,
  },
  {
    word: "Run",
    translation: "correr",
    definition: "To move swiftly on foot.",
    examples: [
      "He runs every morning before work.",
      "The dog loves to run in the park.",
    ],
    tags: [{ id: "V808976mg0fJgf7kwfzd", name: "animal", color: "#FF8A65" }],
    type: "verbo",
    createdAt: "2025-06-25T14:00:00.000Z",
    updatedAt: "2025-06-25T14:00:00.000Z",
    isLearned: false,
  },
  {
    word: "Beautiful",
    translation: "hermoso",
    definition: "Pleasing the senses or mind aesthetically.",
    examples: [
      "The sunset was beautiful.",
      "She wore a beautiful dress to the party.",
    ],
    tags: [{ id: "ZZZSfatMkgfxziESFEsv", name: "rose", color: "#E1BEE7" }],
    type: "adjetivo",
    createdAt: "2025-06-25T15:00:00.000Z",
    updatedAt: "2025-06-25T15:00:00.000Z",
    isLearned: false,
  },
  {
    word: "Elephant",
    translation: "elefante",
    definition: "A large mammal noted for its strength and intelligence.",
    examples: [
      "The elephant used its trunk to grab food.",
      "We saw an elephant at the zoo.",
    ],
    tags: [{ id: "V808976mg0fJgf7kwfzd", name: "animal", color: "#FF8A65" }],
    type: "sustantivo",
    createdAt: "2025-06-25T16:00:00.000Z",
    updatedAt: "2025-06-25T16:00:00.000Z",
    isLearned: false,
  },
];
